name: aws-pipeline
env:
  EB_PACKAGE_S3_BUCKET: "flaskapppackage"
  EB_APP_NAME: "MyFlask"
  ENV_NAME: "MyFlask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-west-1"
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout      
      - uses: actions/checkout@v2

      - name: Package App
        run: zip -r $ {{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: Publish to bucket
        run: 

